# # Accounts and their usage
# l1_chain_1                   | Account #0: 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 (10000 ETH)
# l1_chain_1                   | Private Key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
# l1_chain_1                   |
# l1_chain_1                   | Account #1: 0x70997970c51812dc3a010c7d01b50e0d17dc79c8 (10000 ETH)
# l1_chain_1                   | Private Key: 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
# l1_chain_1                   |
# l1_chain_1                   | Account #2: 0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc (10000 ETH)
# l1_chain_1                   | Private Key: 0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
# l1_chain_1                   |
# l1_chain_1                   | Account #3: 0x90f79bf6eb2c4f870365e785982e1f101e93b906 (10000 ETH)
# l1_chain_1                   | Private Key: 0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6
# l1_chain_1                   |
# l1_chain_1                   | Account #4: 0x15d34aaf54267db7d7c367839aaf71a00a2c6a65 (10000 ETH)
# l1_chain_1                   | Private Key: 0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a
# l1_chain_1                   |
# l1_chain_1                   | Account #5: 0x9965507d1a55bcc2695c58ba16fb37d819b0a4dc (10000 ETH)
# l1_chain_1                   | Private Key: 0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba
# l1_chain_1                   |
# l1_chain_1                   | Account #6: 0x976ea74026e726554db657fa54763abd0c3a0aa9 (10000 ETH)
# l1_chain_1                   | Private Key: 0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e
# l1_chain_1                   |
# l1_chain_1                   | Account #7: 0x14dc79964da2c08b23698b3d3cc7ca32193d9955 (10000 ETH)
# l1_chain_1                   | Private Key: 0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356
# l1_chain_1                   |
# l1_chain_1                   | Account #8: 0x23618e81e3f5cdf7f54c3d65f7fbc0abf5b21e8f (10000 ETH)
# l1_chain_1                   | Private Key: 0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97
# l1_chain_1                   |
# l1_chain_1                   | Account #9: 0xa0ee7a142d267c1f36714e4a8f75612f20a79720 (10000 ETH)
# l1_chain_1                   | Private Key: 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6
# l1_chain_1                   |
# l1_chain_1                   | Account #10: 0xbcd4042de499d14e55001ccbb24a551f3b954096 (10000 ETH)
# l1_chain_1                   | Private Key: 0xf214f2b2cd398c806f84e317254e0f0b801d0643303237d97a22a48e01628897
# l1_chain_1                   |
# l1_chain_1                   | Account #11: 0x71be63f3384f5fb98995898a86b02fb2426c5788 (10000 ETH)
# l1_chain_1                   | Private Key: 0x701b615bbdfb9de65240bc28bd21bbc0d996645a3dd57e7b12bc2bdf6f192c82
# l1_chain_1                   |
# l1_chain_1                   | Account #12: 0xfabb0ac9d68b0b445fb7357272ff202c5651694a (10000 ETH)
# l1_chain_1                   | Private Key: 0xa267530f49f8280200edf313ee7af6b827f2a8bce2897751d06a843f644967b1
# l1_chain_1                   |
# l1_chain_1                   | Account #13: 0x1cbd3b2770909d4e10f157cabc84c7264073c9ec (10000 ETH)
# l1_chain_1                   | Private Key: 0x47c99abed3324a2707c28affff1267e45918ec8c3f20b8aa892e8b065d2942dd
# l1_chain_1                   |
# l1_chain_1                   | Account #14: 0xdf3e18d64bc6a983f673ab319ccae4f1a57c7097 (10000 ETH)
# l1_chain_1                   | Private Key: 0xc526ee95bf44d8fc405a158bb884d9d1238d99f0612e9f33d006bb0789009aaa
# l1_chain_1                   |
# l1_chain_1                   | Account #15: 0xcd3b766ccdd6ae721141f452c550ca635964ce71 (10000 ETH)
# l1_chain_1                   | Private Key: 0x8166f546bab6da521a8369cab06c5d2b9e46670292d85c875ee9ec20e84ffb61
# l1_chain_1                   |
# l1_chain_1                   | Account #16: 0x2546bcd3c84621e976d8185a91a922ae77ecec30 (10000 ETH)
# l1_chain_1                   | Private Key: 0xea6c44ac03bff858b476bba40716402b03e41b8e97e276d1baec7c37d42484a0
# l1_chain_1                   |
# l1_chain_1                   | Account #17: 0xbda5747bfd65f08deb54cb465eb87d40e51b197e (10000 ETH)
# l1_chain_1                   | Private Key: 0x689af8efa8c651a91ad287602527f3af2fe9f6501a7ac4b061667b5a93e037fd
# l1_chain_1                   |
# l1_chain_1                   | Account #18: 0xdd2fd4581271e230360230f9337d5c0430bf44c0 (10000 ETH)
# l1_chain_1                   | Private Key: 0xde9be858da4a475276426320d5e9262ecfc3ba460bfac56360bfa6c4c28b4ee0
# l1_chain_1                   |
# l1_chain_1                   | Account #19: 0x8626f6940e2eb28930efb4cef49b2d1f2c9c1199 (10000 ETH)
# l1_chain_1                   | Private Key: 0xdf57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e

# Account #0
x-deployer_pk: &deployer_pk
  DEPLOYER_PRIVATE_KEY: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'

# Account #8
x-relayer_pk: &relayer_pk
  RELAYER_PRIVATE_KEY: '0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97'

# Account #18
x-fast-relayer_pk: &fast-relayer_pk
  FAST_RELAYER_PRIVATE_KEY: '0xde9be858da4a475276426320d5e9262ecfc3ba460bfac56360bfa6c4c28b4ee0'

# Account #19 - allows the fee test
x-integration_pk: &integration_pk
  PRIVATE_KEY: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'

# Account #19
x-gas-price-oracle_pk: &gas-price-oracle_pk
  GAS_PRICE_ORACLE_OWNER_PRIVATE_KEY: '0xdf57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e'

# Account #14 - allows the fee test
x-integration_2_pk: &integration_2_pk
  PRIVATE_KEY_2: '0xc526ee95bf44d8fc405a158bb884d9d1238d99f0612e9f33d006bb0789009aaa'

# Account #15 - allows the fee test
x-integration_3_pk: &integration_3_pk
  PRIVATE_KEY_3: '0x8166f546bab6da521a8369cab06c5d2b9e46670292d85c875ee9ec20e84ffb61'

version: "3"

services:
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   command:
  #     - --save ""
  #     - --appendonly no
  #make sure you setup proxyd.toml
  # proxyd:
  #   ports:
  #     - 8081:8080
  #   depends_on:
  #     - redis
  #   image: proxyd:latest
  #   volumes:
  #     - ../go/proxyd:/etc/proxyd/
  # this is a helper service used because there's no official hardhat image
  l1_chain:
    image: l1_chain:nix
    ports:
      # expose the service to the host for integration testing
      - ${L1CHAIN_HTTP_PORT:-9545}:8545

  deployer:
    depends_on:
      - l1_chain
      - dtl
    image: deployer:nix
    entrypoint: deployer.sh
    environment:
      FRAUD_PROOF_WINDOW_SECONDS: 0
      L1_NODE_WEB3_URL: http://l1_chain:8545
      # these keys are hardhat's first 2 accounts, DO NOT use in production
      << : *deployer_pk
      << : *relayer_pk
      SEQUENCER_ADDRESS: "0x70997970c51812dc3a010c7d01b50e0d17dc79c8"
      PROPOSER_ADDRESS: "0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc"
      # setting the whitelist owner to address(0) disables the whitelist
      WHITELIST_OWNER: "0x0000000000000000000000000000000000000000"
      L1_FEE_WALLET_ADDRESS: "0x391716d440c151c42cdf1c95c1d83a5427bca52c"
      L2_CHAIN_ID: 31338
      L2_BLOCK_GAS_LIMIT: 11000000
      BLOCK_SIGNER_ADDRESS: "0x00000398232E2064F896018496b4b44b3D62751F"
      GAS_PRICE_ORACLE_OWNER: "0x8626f6940e2eb28930efb4cef49b2d1f2c9c1199"
      GAS_PRICE_ORACLE_OVERHEAD: "2750"
      GAS_PRICE_ORACLE_SCALAR: "1500000"
      GAS_PRICE_ORACLE_L1_BASE_FEE: "1"
      GAS_PRICE_ORACLE_GAS_PRICE: "1000000000"
      GAS_PRICE_ORACLE_DECIMALS: "6"
      # skip compilation when run in docker-compose, since the contracts
      # were already compiled in the builder step
      NO_COMPILE: 1
      DTL_REGISTRY_URL: http://dtl:8081/addresses.json
      DTL_STATE_DUMP_REGISTRY_URL: http://dtl:8081/state-dump.latest.json
    ports:
        # expose the service to the host for getting the contract addrs
      - ${DEPLOYER_PORT:-8077}:8082

      # deploys boba contracts and serves contract addresses
  boba_deployer:
    depends_on:
      - l1_chain
      - dtl
      - l2geth
    image: boba_deployer:nix
    environment:
      L1_NODE_WEB3_URL: http://l1_chain:8545
      L2_NODE_WEB3_URL: http://l2geth:8545
      ADDRESS_MANAGER_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
      URL: http://dtl:8081/addresses.json
      # DO NOT use in production
      << : *deployer_pk
      << : *relayer_pk
      << : *fast-relayer_pk
      RETRIES: 200
      DTL_REGISTRY_URL: http://dtl:8081/boba-addr.json
      # skip compilation when run in docker-compose, since the contracts
      # were already compiled in the builder step
      NO_COMPILE: 1

  dtl:
    depends_on:
      - l1_chain
    image: dtl:nix
    # override with the dtl script and the env vars required for it
    env_file:
      -  ./envs/dtl.env
    # set the rest of the env vars for the network whcih do not
    # depend on the docker-compose setup
    environment:
      URL: http://deployer:8082/addresses.json
      # connect to the 2 layers
      DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: http://l1_chain:8545
      DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: http://l2geth:8545
      DATA_TRANSPORT_LAYER__SYNC_FROM_L2: 'true'
      DATA_TRANSPORT_LAYER__L2_CHAIN_ID: 31338
      DATA_TRANSPORT_LAYER__BSS_HARDFORK_1_INDEX: 0
      DATA_TRANSPORT_LAYER__ETH1_CTC_DEPLOYMENT_HEIGHT: 0
      RETRIES: 200
      # if no need to support Turing v0 set height of v0 = v1
      DATA_TRANSPORT_LAYER__TURING_V0_HEIGHT: 0
      DATA_TRANSPORT_LAYER__TURING_V1_HEIGHT: 0
    ports:
      - ${DTL_PORT:-7878}:7878
      - ${REGISTRY_PORT:-8080}:8081

  l2geth:
    depends_on:
      - l1_chain
      - dtl
    image: l2geth:nix
    # override with the geth script and the env vars required for it
    #entrypoint: l2geth-start
    env_file:
      - ./envs/geth.env
    restart: always
    environment:
      ETH1_HTTP: http://l1_chain:8545
      ROLLUP_TIMESTAMP_REFRESH: 5s
      ROLLUP_STATE_DUMP_PATH: http://dtl:8081/state-dump.latest.json
      # connecting to the DTL
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      RETRIES: 200
      # no need to keep this secret, only used internally to sign blocks
      BLOCK_SIGNER_KEY: "6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27"
      BLOCK_SIGNER_ADDRESS: "0x00000398232E2064F896018496b4b44b3D62751F"
      TURING_CREDIT_ADDRESS: "0x4200000000000000000000000000000000000020"
      EMERGENCY_FORK_NUMBER: 0
      L2_BOBA_TOKEN_ADDRESS: "0x4200000000000000000000000000000000000023"
      BOBA_GAS_PRICE_ORACLE_ADDRESS: "0x4200000000000000000000000000000000000024"
    ports:
      - ${L2GETH_HTTP_PORT:-8545}:8545
      - ${L2GETH_WS_PORT:-8546}:8546

  batch_submitter:
    restart: always
    depends_on:
      - l1_chain
      - dtl
      - l2geth
      - kms
    image: go-batch-submitter:nix
    entrypoint: batch-submitter.sh
    env_file:
      - ./envs/batch-submitter.env
    environment:
      L1_ETH_RPC: http://l1_chain:8545
      L2_ETH_RPC: http://l2geth:8545
      URL: http://dtl:8081/addresses.json
      RETRIES: 200
      #KMS access setup
      AWS_ACCESS_KEY_ID: "1"
      AWS_SECRET_ACCESS_KEY: "11"
      BATCH_SUBMITTER_KMS_ENDPOINT: http://kms:8888/
      BATCH_SUBMITTER_KMS_REGION: us-east-1
      #aliases are setup, check seed.yml
      BATCH_SUBMITTER_SEQUENCER_KEY_ID: "0x70997970c51812dc3a010c7d01b50e0d17dc79c8"
      BATCH_SUBMITTER_PROPOSER_KEY_ID: "0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc"

  # verifier:
  #   depends_on:
  #     - dtl
  #   image: l2geth:nix
  #   deploy:
  #     replicas: 1
  #   entrypoint: sh ./geth.sh
  #   env_file:
  #     - ./envs/geth.env
  #   environment:
  #       ETH1_HTTP: http://l1_chain:8545
  #       ROLLUP_TIMESTAMP_REFRESH: 5s
  #       ROLLUP_STATE_DUMP_PATH: http://dtl:8081/state-dump.latest.json
  #       ROLLUP_CLIENT_HTTP: http://dtl:7878
  #       ROLLUP_BACKEND: 'l1'
  #       ROLLUP_VERIFIER_ENABLE: 'true'
  #       RETRIES: 60
  #       # no need to keep this secret, only used internally to sign blocks
  #       BLOCK_SIGNER_KEY: "6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27"
  #       BLOCK_SIGNER_ADDRESS: "0x00000398232E2064F896018496b4b44b3D62751F"
  #       ROLLUP_POLL_INTERVAL_FLAG: "10s"
  #       TURING_CREDIT_ADDRESS: "0x4200000000000000000000000000000000000020"
  #       EMERGENCY_FORK_NUMBER: 0
  #       L2_BOBA_TOKEN_ADDRESS: "0x4200000000000000000000000000000000000023"
  #       BOBA_GAS_PRICE_ORACLE_ADDRESS: "0x4200000000000000000000000000000000000024"
  #   ports:
  #     - ${VERIFIER_HTTP_PORT:-8547}:8545
  #     - ${VERIFIER_WS_PORT:-8548}:8546

  gas_oracle:
    depends_on:
      - l1_chain
      - l2geth
    image: boba_gas-price-oracle:nix
    environment:
      ADDRESS_MANAGER_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
      L1_NODE_WEB3_URL: http://l1_chain:8545
      L2_NODE_WEB3_URL: http://l2geth:8545
      GAS_PRICE_ORACLE_ADDRESS: "0x420000000000000000000000000000000000000F"
      ADDRESS_MANAGER_ADDRESS: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
      << : *gas-price-oracle_pk #same as the deployer
      << : *relayer_pk
      << : *fast-relayer_pk
      SEQUENCER_ADDRESS: "0x70997970c51812dc3a010c7d01b50e0d17dc79c8"
      PROPOSER_ADDRESS: "0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc"
      GAS_PRICE_ORACLE_FLOOR_PRICE: 1
      GAS_PRICE_ORACLE_ROOF_PRICE: 5
      GAS_PRICE_ORACLE_MIN_PERCENT_CHANGE:
      POLLING_INTERVAL:
      RETRIES: 200


  #in no way should this be running in production
  kms:
    image: bobanetwork/local-kms:latest
    environment:
      PORT: "8888"
      KMS_REGION: "us-east-1"
    volumes:
      - type: bind
        source: ./seed.yaml
        target: /init/seed.yaml
    ports:
      - 8888:8888
