version: "3"

# An "--env-file" must be supplied to docker-compose. Example:
#   docker-compose
#     -f docker-compose-fraud-detector.yml \
#     --env-file deployments/local/env \
#     build
# For non-local targets, INFURA_API_KEY must also be set
networks:
  default:
    external: true
    name: ops_default

services:
  verifier_dtl:
    image: bobanetwork/verifier_dtl:${TARGET_NAME}
    build:
      context: ../..
      dockerfile: ./boba_community/fraud-detector/docker/Dockerfile.verifier_dtl
      args:
        TARGET_NAME: ${TARGET_NAME}
    env_file:
      -  ../../ops/envs/dtl.env
    environment:
        DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: ${L1_RPC_ENDPOINT}
        DATA_TRANSPORT_LAYER__CONFIRMATIONS: 8
        DATA_TRANSPORT_LAYER__SYNC_FROM_L2: 'false'
        DATA_TRANSPORT_LAYER__L2_CHAIN_ID: ${L2_CHAIN_ID}
        DATA_TRANSPORT_LAYER__ADDRESS_MANAGER: ${ADDRESS_MANAGER}
        DATA_TRANSPORT_LAYER__POLLING_INTERVAL: 10000
        DATA_TRANSPORT_LAYER__ETH1_CTC_DEPLOYMENT_HEIGHT: ${ETH1_CTC_DEPLOYMENT_HEIGHT}
#    ports:
#      - ${DTL_PORT:-7878}:7878
#      - ${REGISTRY_PORT:-8080}:8081
#    volumes:
#      - /var/tmp/verifier/dtl_db:/db

  verifier_l2geth:
    depends_on:
      - verifier_dtl
    image: bobanetwork/l2geth:${TARGET_NAME}
    deploy:
      replicas: 1
    build:
      context: ../..
      dockerfile: ./ops/docker/Dockerfile.geth
    entrypoint: sh ./geth.sh
    env_file:
      - ../../ops//envs/geth.env
    environment:
        ROLLUP_TIMESTAMP_REFRESH: 5s
        ROLLUP_STATE_DUMP_PATH: http://verifier_dtl:8081/state-dump.latest.json
        ROLLUP_CLIENT_HTTP: http://verifier_dtl:7878
        ROLLUP_BACKEND: 'l1'
        ROLLUP_VERIFIER_ENABLE: 'true'
        RETRIES: 60
        # no need to keep this secret, only used internally to sign blocks
        BLOCK_SIGNER_KEY: "6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27"
        BLOCK_SIGNER_ADDRESS: "0x00000398232E2064F896018496b4b44b3D62751F"
        ROLLUP_POLL_INTERVAL_FLAG: "10s"
    ports:
      - ${VERIFIER_HTTP_PORT:-8547}:8545
      - ${VERIFIER_WS_PORT:-8548}:8546
#    volumes:
#      - /var/tmp/verifier/l2geth_vol:/root/.ethereum

  fraud-detector:
    depends_on:
     - verifier_dtl
     - verifier_l2geth
    image: bobanetwork/fraud-detector:${TARGET_NAME}
    deploy:
      replicas: 1
    build:
      context: ../..
      dockerfile: ./boba_community/fraud-detector/docker/Dockerfile.fraud-detector
    environment:
      L1_NODE_WEB3_URL: ${L1_RPC_ENDPOINT}
      L1_CONFIRMATIONS: 8
      L2_NODE_WEB3_URL: ${L2_RPC_ENDPOINT}
      L2_CHECK_INTERVAL: 10
      VERIFIER_WEB3_URL: http://verifier_l2geth:8545
      ADDRESS_MANAGER_ADDRESS: ${ADDRESS_MANAGER}
      L1_DEPLOYMENT_BLOCK: ${ETH1_CTC_DEPLOYMENT_HEIGHT}
      L2_START_BLOCK: 1
    ports:
      - ${FRAUD_CHECKER_HTTP_PORT:-8555}:8555
 
