




# # Accounts and their usage
# l1_chain_1                   | Account #0: 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 (10000 ETH)
# l1_chain_1                   | Private Key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
# l1_chain_1                   |
# l1_chain_1                   | Account #1: 0x70997970c51812dc3a010c7d01b50e0d17dc79c8 (10000 ETH)
# l1_chain_1                   | Private Key: 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
# l1_chain_1                   |
# l1_chain_1                   | Account #2: 0x3c44cdddb6a900fa2b585dd299e03d12fa4293bc (10000 ETH)
# l1_chain_1                   | Private Key: 0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
# l1_chain_1                   |
# l1_chain_1                   | Account #3: 0x90f79bf6eb2c4f870365e785982e1f101e93b906 (10000 ETH)
# l1_chain_1                   | Private Key: 0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6
# l1_chain_1                   |
# l1_chain_1                   | Account #4: 0x15d34aaf54267db7d7c367839aaf71a00a2c6a65 (10000 ETH)
# l1_chain_1                   | Private Key: 0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a
# l1_chain_1                   |
# l1_chain_1                   | Account #5: 0x9965507d1a55bcc2695c58ba16fb37d819b0a4dc (10000 ETH)
# l1_chain_1                   | Private Key: 0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba
# l1_chain_1                   |
# l1_chain_1                   | Account #6: 0x976ea74026e726554db657fa54763abd0c3a0aa9 (10000 ETH)
# l1_chain_1                   | Private Key: 0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e
# l1_chain_1                   |
# l1_chain_1                   | Account #7: 0x14dc79964da2c08b23698b3d3cc7ca32193d9955 (10000 ETH)
# l1_chain_1                   | Private Key: 0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356
# l1_chain_1                   |
# l1_chain_1                   | Account #8: 0x23618e81e3f5cdf7f54c3d65f7fbc0abf5b21e8f (10000 ETH)
# l1_chain_1                   | Private Key: 0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97
# l1_chain_1                   |
# l1_chain_1                   | Account #9: 0xa0ee7a142d267c1f36714e4a8f75612f20a79720 (10000 ETH)
# l1_chain_1                   | Private Key: 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6
# l1_chain_1                   |
# l1_chain_1                   | Account #10: 0xbcd4042de499d14e55001ccbb24a551f3b954096 (10000 ETH)
# l1_chain_1                   | Private Key: 0xf214f2b2cd398c806f84e317254e0f0b801d0643303237d97a22a48e01628897
# l1_chain_1                   |
# l1_chain_1                   | Account #11: 0x71be63f3384f5fb98995898a86b02fb2426c5788 (10000 ETH)
# l1_chain_1                   | Private Key: 0x701b615bbdfb9de65240bc28bd21bbc0d996645a3dd57e7b12bc2bdf6f192c82
# l1_chain_1                   |
# l1_chain_1                   | Account #12: 0xfabb0ac9d68b0b445fb7357272ff202c5651694a (10000 ETH)
# l1_chain_1                   | Private Key: 0xa267530f49f8280200edf313ee7af6b827f2a8bce2897751d06a843f644967b1
# l1_chain_1                   |
# l1_chain_1                   | Account #13: 0x1cbd3b2770909d4e10f157cabc84c7264073c9ec (10000 ETH)
# l1_chain_1                   | Private Key: 0x47c99abed3324a2707c28affff1267e45918ec8c3f20b8aa892e8b065d2942dd
# l1_chain_1                   |
# l1_chain_1                   | Account #14: 0xdf3e18d64bc6a983f673ab319ccae4f1a57c7097 (10000 ETH)
# l1_chain_1                   | Private Key: 0xc526ee95bf44d8fc405a158bb884d9d1238d99f0612e9f33d006bb0789009aaa
# l1_chain_1                   |
# l1_chain_1                   | Account #15: 0xcd3b766ccdd6ae721141f452c550ca635964ce71 (10000 ETH)
# l1_chain_1                   | Private Key: 0x8166f546bab6da521a8369cab06c5d2b9e46670292d85c875ee9ec20e84ffb61
# l1_chain_1                   |
# l1_chain_1                   | Account #16: 0x2546bcd3c84621e976d8185a91a922ae77ecec30 (10000 ETH)
# l1_chain_1                   | Private Key: 0xea6c44ac03bff858b476bba40716402b03e41b8e97e276d1baec7c37d42484a0
# l1_chain_1                   |
# l1_chain_1                   | Account #17: 0xbda5747bfd65f08deb54cb465eb87d40e51b197e (10000 ETH)
# l1_chain_1                   | Private Key: 0x689af8efa8c651a91ad287602527f3af2fe9f6501a7ac4b061667b5a93e037fd
# l1_chain_1                   |
# l1_chain_1                   | Account #18: 0xdd2fd4581271e230360230f9337d5c0430bf44c0 (10000 ETH)
# l1_chain_1                   | Private Key: 0xde9be858da4a475276426320d5e9262ecfc3ba460bfac56360bfa6c4c28b4ee0
# l1_chain_1                   |
# l1_chain_1                   | Account #19: 0x8626f6940e2eb28930efb4cef49b2d1f2c9c1199 (10000 ETH)
# l1_chain_1                   | Private Key: 0xdf57089febbacf7ba0bc227dafbffa9fc08a93fdc68e1e42411a14efcf23656e

# Account #0
x-deployer_pk: &deployer_pk
  DEPLOYER_PRIVATE_KEY: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'

# Account #8
x-relayer_pk: &relayer_pk
  RELAYER_PRIVATE_KEY: '0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97'

# Account #18
x-fast-relayer_pk: &fast-relayer_pk
  FAST_RELAYER_PRIVATE_KEY: '0xde9be858da4a475276426320d5e9262ecfc3ba460bfac56360bfa6c4c28b4ee0'

# Account #19 - allows the fee test
x-integration_pk: &integration_pk
  PRIVATE_KEY: '0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'

# Account #14 - allows the fee test
x-integration_2_pk: &integration_2_pk
  PRIVATE_KEY_2: '0xc526ee95bf44d8fc405a158bb884d9d1238d99f0612e9f33d006bb0789009aaa'

# Account #15 - allows the fee test
x-integration_3_pk: &integration_3_pk
  PRIVATE_KEY_3: '0x8166f546bab6da521a8369cab06c5d2b9e46670292d85c875ee9ec20e84ffb61'

version: "3"

services:

  # this is a helper service used because there's no official hardhat image
  #l1_chain:
  #  image: bobanetwork/hardhat:latest
  #  build:
  #    context: ./docker/hardhat
  #    dockerfile: Dockerfile
  #  ports:
  #    # expose the service to the host for integration testing
  #    - ${L1CHAIN_HTTP_PORT:-9545}:8545
  erigon_base:
    # Adapted from ../bedrock/erigon/docker-compose.yml
    image: bobanetwork/erigon-base:${TAG:-latest}
   # build:
   #   args:
   #     UID: ${DOCKER_UID}
   #     GID: ${DOCKER_GID}
   #   context: ..
   #   dockerfile: bedrock/erigon/Dockerfile
    user: "${DOCKER_UID}:${DOCKER_GID}"
    command: |
      erigon ${ERIGON_FLAGS-} --private.api.addr=0.0.0.0:9090
      --sentry.api.addr=sentry:9091 --downloader.api.addr=downloader:9093 --txpool.disable
      --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --pprof --pprof.addr=0.0.0.0 --pprof.port=6061
    deploy:
      replicas: 0

  l1_execution_client:
    depends_on:
      - erigon_base
    image: bobanetwork/l1-erigon
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.l1-erigon
    environment:
      CHAIN_ID: 31337    # 31337 matches Hardhat's default
      BLOCK_INTERVAL: 0  # 0 = auto-mine
    volumes:
      - type: bind
        source: "${PWD}/ops/volumes/l1_execution_client_data"
        target: /erigon-data
    ports:
      - ${L1CHAIN_HTTP_PORT:-9545}:8545
      - "30303:30303/tcp"
      - "30303:30303/udp"
      - "42069:42069/tcp"
      - "42069:42069/udp"
    mem_swappiness: 0


  # Consensus layer:
  # docker run -it -v "${PWD}/ops/volumes/l1_execution_client_data/jwt.hex":"/app/cmd/beacon-chain/beacon-chain.runfiles/prysm/cmd/jwt.hex" -p 4000:4000 -p 13000:13000 -p 12000:12000/udp   gcr.io/prysmaticlabs/prysm/beacon-chain:stable   --datadir=/data   --rpc-host=0.0.0.0   --monitoring-host=0.0.0.0   --http-web3provider=http://host.docker.internal:8551 --jwt-secret="/app/cmd/beacon-chain/beacon-chain.runfiles/prysm/cmd/jwt.hex" --accept-terms-of-use
  l1_consensus_client:
    depends_on:
      - l1_execution_client
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v2.1.3
    container_name: beacon-node
    restart: on-failure
    healthcheck:
      test: [ "CMD", "-f", "/erigon-data/jwt.hex" ]
      retries: 5
      timeout: 20s
    ports:
      - "4000:4000"
      - "13000:13000"
      - "12000:12000/udp"
    volumes:
      - type: bind
        source: "${PWD}/ops/volumes/l1_execution_client_data"
        target: /erigon-data
      - type: bind
        source: "${PWD}/ops/volumes/l1_consensus_client_data"
        target: /data
      #- "${PWD}/ops/volumes/l1_execution_client_data/:/app/cmd/beacon-chain/beacon-chain.runfiles/prysm/" # for auth
      #--checkpoint-sync-url=http://l1_execution_client --genesis-beacon-api-url=http://l1_execution_client --enable-debug-rpc-endpoints
      # --weak-subjectivity-checkpoint
    command: --datadir=/data --sepolia --chain-id=31337 --suggested-fee-recipient=0x21709a12f1aa73A6758905F5e92fFaD03d394E89 --force-clear-db --rpc-host=0.0.0.0 --monitoring-host=0.0.0.0 --http-web3provider=http://l1_execution_client:8551 --jwt-secret="/erigon-data/jwt.hex" --accept-terms-of-use #--terminal-total-difficulty-override=17000000000000000 #--genesis-state=/genesis.ssz
    mem_swappiness: 0


